# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: API Gateway Secure Stream Store
  description: Stream store sample that uses Cognito Developer Authenticated Identities to generate credentials through a Java Lambda Function
  version: "1.0.0"
# the domain of the service
host: execute-api.us-east-1.amazonaws.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /users:
    post:
      summary: Registers a new user
      description: |
        Creates a new user in the DynamoDB backend database and returns a set
        of temporary credentials to sign future requests.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: NewUser
          in: body
          description: New user details.
          schema:
            $ref: '#/definitions/User'
      tags:
        - Auth
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:1add9a6f-1496-4ff6-a610-215aa4403f51:function:livecooktv-api/invocations
        credentials: arn:aws:iam::766545951932:role/Cognito_livecooktvUnauth_Role
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "action" : "com.amazonaws.apigatewaydemo.action.RegisterDemoAction",
              "body" : $input.json('$')
            }
        responses:
          "default":
            statusCode: "200"
          "BAD.*":
            statusCode: "400"
          "INT.*":
            statusCode: "500"
      responses:
        200:
          description: The username of the new user and set of temporary credentials
          schema:
            $ref: '#/definitions/RegisterUserResponse'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
  /login:
    post:
      summary: Login user
      description: |
        Verifies the given credentials against the user database and returns a set
        of new temporary credentials
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: LoginUser
          in: body
          description: New user details.
          schema:
            $ref: '#/definitions/User'
      tags:
        - Auth
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:1add9a6f-1496-4ff6-a610-215aa4403f51:function:livecooktv-api/invocations
        credentials: arn:aws:cognito-identity:us-east-1:766545951932:identitypool/us-east-1:1add9a6f-1496-4ff6-a610-215aa4403f51
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "action" : "com.amazonaws.apigatewaydemo.action.LoginDemoAction",
              "body" : $input.json('$')
            }
        responses:
          "default":
            statusCode: "200"
          "BAD.*":
            statusCode: "400"
          "INT.*":
            statusCode: "500"
      responses:
        200:
          description: A new set of temporary credentials
          schema:
            $ref: '#/definitions/LoginUserResponse'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
  /streams:
    post:
      summary: Creates a new streams
      description: |
        Creates a new stream object in the datastore
      x-amazon-apigateway-auth:
        type: aws_iam
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: NewStream
          in: body
          description: New stream details.
          schema:
            $ref: '#/definitions/NewStream'
      tags:
        - Stream Store
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:1add9a6f-1496-4ff6-a610-215aa4403f51:function:livecooktv-api/invocations
        credentials: arn:aws:iam::*:user/*
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "action" : "com.amazonaws.apigatewaydemo.action.CreateStreamDemoAction",
              "body" : $input.json('$')
            }
        responses:
          "default":
            statusCode: "200"
          "BAD.*":
            statusCode: "400"
          "INT.*":
            statusCode: "500"
      responses:
        200:
          description: The unique identifier of the new stream
          schema:
            $ref: '#/definitions/NewStreamResponse'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
    get:
      summary: List streams
      description: Retrieve a list of streams in the store
      x-amazon-apigateway-auth:
        type: aws_iam
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - Stream Store
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:1add9a6f-1496-4ff6-a610-215aa4403f51:function:livecooktv-api/invocations
        credentials: arn:aws:iam::*:user/*
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "action" : "com.amazonaws.apigatewaydemo.action.ListStreamsDemoAction",
              "body" : $input.json('$')
            }
        responses:
          "default":
            statusCode: "200"
          "BAD.*":
            statusCode: "400"
          "INT.*":
            statusCode: "500"
      responses:
        200:
          description: A list of streams
          schema:
            $ref: '#/definitions/Streams'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
  /streams/{streamId}:
    get:
      summary: Get stream by id
      description: Returns a stream definition based on the given id
      x-amazon-apigateway-auth:
        type: aws_iam
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - Stream Store
      parameters:
        - name: streamId
          in: path
          description: The unique identifier for a stream
          type: string
      x-amazon-apigateway-integration:
        type: aws
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:1add9a6f-1496-4ff6-a610-215aa4403f51:function:livecooktv-api/invocations
        credentials: arn:aws:iam::*:user/*
        httpMethod: POST
        requestTemplates:
          application/json: |
            {
              "action" : "com.amazonaws.apigatewaydemo.action.GetStreamDemoAction",
              "body" : {
                "streamId" : "$input.params('streamId')"
              }
            }
        responses:
          "default":
            statusCode: "200"
          "BAD.*":
            statusCode: "400"
          "INT.*":
            statusCode: "500"
      responses:
        200:
          description: A stream
          schema:
            $ref: '#/definitions/Stream'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
definitions:
  User:
    properties:
      username:
        type: string
        description: A unique username for the user
      password:
        type: string
        description: A password for the new user
  RegisterUserResponse:
    properties:
      username:
        type: string
        description: The username of the new user
      identityId:
        type: string
        description: The unique identifier for the new user
      token:
        type: string
        description: An OpenID token for the new user
      credentials:
        properties:
          accessKey:
            type: string
            description: Temporary access key to sign requests
          secretKey:
            type: string
            description: Temporary secret access key to sign requests
          sessionToken:
            type: string
            description: Tempoarary session token
          expiration:
            type: integer
            description: |
              Expiration date of the temporary credentials in millis since 1/1/1970
  LoginUserResponse:
    properties:
      identityId:
        type: string
        description: The unique identifier for the new user
      token:
        type: string
        description: An OpenID token for the new user
      credentials:
        properties:
          accessKey:
            type: string
            description: Temporary access key to sign requests
          secretKey:
            type: string
            description: Temporary secret access key to sign requests
          sessionToken:
            type: string
            description: Tempoarary session token
          expiration:
            type: integer
            description: |
              Expiration date of the temporary credentials in millis since 1/1/1970
  NewStream:
    properties:
      streamType:
        type: string
        description: Free text stream type
      streamName:
        type: string
        description: Free text stream name
      streamAge:
        type: integer
        description: Age of the new stream
  NewStreamResponse:
    properties:
      streamId:
        type: string
        description: The generated unique identifier for the new stream
  Stream:
    properties:
      streamId:
        type: string
        description: The generated unique identifier for the new stream
      streamType:
        type: string
        description: Free text stream type
      streamName:
        type: string
        description: Free text stream name
      streamAge:
        type: integer
        description: Age of the new stream
  Streams:
    type: array
    items:
      $ref: Stream
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
